### ISSUE TITLE
Zookeeper init container assumes only one host:port in zkAddress config

### ISSUE THREAD

**Issue by michael81877** [konpyutaika/nifikop#187]
### What steps will reproduce the bug?

Context: https://konpytika.slack.com/archives/C035X6KP684/p1666601342444459

nifikop assumes a single zookeeper `host:port` combination provided as a part of the `NifiCluster.Spec.zkAddress` configuration. This is fine when zookeeper is deployed in Kubernetes behind a `Service` DNS name. However, when the zookeeper is deployed external from Kubernetes, it's still necessary to provide a comma-delimited list of `host:port` pairs as documented [here](https://javadoc.io/doc/org.apache.zookeeper/zookeeper/latest/index.html).

nifikop uses the connect string in a NiFi init container to ensure that the configured zookeeper is available prior to starting NiFi pods. The logic it uses to acquire host and port configurations from the `zkAddress` is [here](https://github.com/konpyutaika/nifikop/blob/master/pkg/util/zookeeper/common.go#L11-L17).

### What is the expected behavior?

nifikop should tolerate all valid zookeeper connection strings. For example:

- `host1:2181`
- `host1:2181,host2:2181`
- `host1:2181,host2:2181,host3:2181`

### What do you see instead?

nifikop cannot handle more than a single `host:port` pair configured for the `zkAddress`

### NiFiKop version

all

### Golang version

go1.19

### Kubernetes version

1.24

### NiFi version

all

### Additional context

Context: https://konpytika.slack.com/archives/C035X6KP684/p1666601342444459

**Comment by nbonavia** [comment]
To further add on top of this issue, it seems that the problem lies in the zookeeper initContainer (extract below) which waits for an active zookeeper. Unfortunately the below script is not parsing the zookeeper nodes properly

```
- command:
    - sh
    - -c
    - "\necho trying to contact Zookeeper: host1:2181,host2:2181,host3:2181;
      nc -vzw 1 host1 2181,host2;
      do\n\techo \"waiting for zookeeper...\"\n\tsleep 2\ndone"
    image: busybox:1.35.0
    imagePullPolicy: IfNotPresent
    name: zookeeper
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wdc45
      readOnly: true
```

**Comment by nbonavia** [comment]
Just to drop a follow-up here, I have created a quick initContainer that can verify multiple zookeeper nodes before a pod is started.

```
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-checker-script
spec:
  initContainers:
  - name: zookeeper
    image: bash:5.2.2-alpine3.15
    imagePullPolicy: IfNotPresent
    command: 
    - bash
    - -c
    - |
      set -e
      echo trying to contact Zookeeper: ${ZK_ADDRESS}
​
      IFS=',' read -r -a zk_hosts <<< "${ZK_ADDRESS}"
      for zk_host in "${zk_hosts[@]}"
      do
        IFS=':' read -r -a zk_host_port <<< "${zk_host}"
        
        echo "Checking Zookeeper Host: [${zk_host_port[0]}] Port: [${zk_host_port[1]}]:"
        until nc -vzw 1 ${zk_host_port[0]} ${zk_host_port[1]}
        do
          echo "waiting for Host: [${zk_host_port[0]}] Port: [${zk_host_port[1]}] ... "
          sleep 2
        done
      done
    env:
    - name: ZK_ADDRESS
      value: host.k3d.internal:2181,host.k3d.internal:2181,host.k3d.internal:2181
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  containers:
  - name: main
    image: busybox:1.35.0
    imagePullPolicy: IfNotPresent
    command: 
      - sh
      - -c
      - |
        tail -f /dev/null
    resources: {}
```
