### ISSUE TITLE
Nifi in cluster and secured with istio gateway

### ISSUE THREAD

**Issue by ggerla** [konpyutaika/nifikop#225]
Hi all
I need to deploy a Nifi cluster with https enabled. I have neither LDAP or Keycloak, so I would like to configure only one admin user.
Because my K8S is using istio I configured a gateway and a virtual service to allow access to the cluster from external world.
I created a secret with my CA and then an issuer.
I deployed the operator with this configuration

```
image:
  repository: quay.io/konpyutaika/docker-images/nifikop

namespaces:
- nifi
- cert-manager
```

and finally deployed the cluster 

```
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: sslnifi
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: sslnifi
  zkAddress: "zookeeper.nifi.svc.cluster.local:2181"
  zkPath: "/ssllnifinodes"
  clusterImage: "proxy-ext.docker.at.thales/apache/nifi:1.17.0"
  initContainerImage: 'artifactory.prz.ics.eu-west-1.aws.gts/public_docker/library/bash:5.2.2'
  oneNifiNodePerNode: true
  externalServices:
#    - metadata:
#        labels:
#          cluster-name: sslnifi
#      name: driver-ip
#      spec:
#        portConfigs:
#          - internalListenerName: https
#            port: 8443
#        type: LoadBalancer
    - name: "nifi-cluster"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8443
            internalListenerName: "https"   
  managedAdminUsers:
    - identity : "CN=admin"
      name: "admin"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  readOnlyConfig:
    # NifiProperties configuration that will be applied to the node.
    nifiProperties:
      webProxyHosts:
        - nifi.my-domain.com:443
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
        nifi.security.identity.mapping.pattern.dn=CN=([^,]*)(?:, (?:O|OU)=.*)?
        nifi.security.identity.mapping.value.dn=$1
        nifi.security.identity.mapping.transform.dn=NONE
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/data"
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/flowfile_repository"
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/nifi-current/conf"
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/content_repository"
          name: content-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/provenance_repository"
          name: provenance-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-sc-delete"
            resources:
              requests:
                storage: 10Gi
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 1Gi
  nodes:
    - id: 0
      nodeConfigGroup: "default_group"
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
#      - type: "load-balance"
#        name: "load-balance"
#        containerPort: 6342
    sslSecrets:
      tlsSecretName: "sslnifi-secret"
      create: true
      clusterScoped: true
      issuerRef:
        name: nifi-ca-issuer
        kind: Issuer
```

The cluster seems to start properly but if I try to access to the UI I receive the following error

![image](https://user-images.githubusercontent.com/5663231/213663844-aed4262b-3f8c-4b69-bdad-8c5f31670a2a.png)

Do you have any idea on how to solve this issue?
