### ISSUE TITLE
Ability to set port for NodePort type service

### ISSUE THREAD

**Issue by bngsudheer** [konpyutaika/nifikop#283]
### Type of question

Implementation Assistance

### Support question

I have this example config:
```
      externalServices:
            - metadata:
              labels:
                cluster-name: driver-xxx
              name: xxx-nifi-access
              spec:
                portConfigs:
                  - internalListenerName: http
                    port: 8080
                    nodePort: 32626
                type: NodePort
```
I have tried setting nodePort to a specific port 32626, but the service uses a random port. How do I set a specific port with NodePort type service?
