### ISSUE TITLE
Enable singleUserConfiguration Not work

### ISSUE THREAD

**Issue by tim64195419** [konpyutaika/nifikop#334]
### What steps will reproduce the bug?

When I enabled singleUserConfiguration，but nifi pod did not start normally
```
  singleUserConfiguration:
    enabled: true
    authorizerEnabled: false
    secretRef:
      name: "single-user-credentials"
      namespace: "nifi"
    secretKeys:
      username: "username"
      password: "password"
```
I found that the authors.xml file could not be found in the path
![image](https://github.com/konpyutaika/nifikop/assets/14270024/efad5a0c-5171-4daf-9505-8e3fd4dc5e38)

### What is the expected behavior?

I expected that the pod should find the authors.xml file and start normally

### What do you see instead?

ssh into the pod and see that the file does not exist in the conf path.
![image](https://github.com/konpyutaika/nifikop/assets/14270024/76886da4-8e3c-4f71-95fc-6c3251e5b1f9)

### NiFiKop version

v1.5.0

### Golang version

go v1.20

### Kubernetes version

v1.28.2

**Comment by juldrixx** [comment]
Hi,

Can you try with

```yaml
 singleUserConfiguration:
    enabled: true
    authorizerEnabled: true <---
    secretRef:
      name: "single-user-credentials"
      namespace: "nifi"
    secretKeys:
      username: "username"
      password: "password"
```
