### ISSUE TITLE
nifikop 1.6.0 duplicates flow on canvas (deploys two instead of one)

### ISSUE THREAD

**Issue by mostafamohajeri** [konpyutaika/nifikop#346]
### What steps will reproduce the bug?

Hi, thanks for the help and the work, here's the method to reproduce

1. In minikube
2. follow the starting guide
3. start minikube `minikube start --driver=docker --cpus=2 --memory=8000 --extra-config=kubelet.cgroup-driver=systemd`
4. install cert-manager `kubectl apply -f     https://github.com/jetstack/cert-manager/releases/download/v1.7.2/cert-manager.yaml`
5. install nifikop `helm install nifikop     oci://ghcr.io/konpyutaika/helm-charts/nifikop     --namespace=nifi     --version 1.6.0     --set image.tag=v1.6.0-release     --set resources.requests.memory=256Mi     --set resources.requests.cpu=250m   
   --set resources.limits.memory=256Mi     --set resources.limits.cpu=250m     --set namespaces={"nifi"} --create-namespace`
6. deploy zookeeper `helm install zookeeper bitnami/zookeeper     --namespace=zookeeper     --set resources.requests.memory=256Mi     --set resources.requests.cpu=250m     --set resources.limits.memory=256Mi     --set resources.limits.cpu=250m     --set global.storageClass=standard     --set networkPolicy.enabled=true     --set replicaCount=1     --create-namespace`

deploy everything:
1. `kubectl apply -f cluster.yaml -n nifi`
2. `kubectl apply -f paramcontext.yaml -n nifi`
3. `kubectl apply -f registry.yaml -n nifi`
4. `kubectl apply -f flow.yaml -n nifi`

### cluster
```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: simplenifi
  zkAddress: "zookeeper.zookeeper:2181"
  zkPath: /simplenifi
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-simplenifi
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 18443
        type: LoadBalancer
  clusterImage: "apache/nifi:1.23.2"
  initContainerImage: "bash:5.2.2"
  oneNifiNodePerNode: true
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  pod:
    labels:
      cluster-name: simplenifi
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: default
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 1Gi
      resourcesRequirements:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - containerPort: 8443
        type: http
        name: http
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 9090
        type: prometheus
        name: prometheus
      - containerPort: 6342
        type: load-balance
        name: load-balance

```
### param context
```yaml
# kubectl create secret generic secret-params --from-literal=secret1=yop --from-literal=secret2=yep
apiVersion: nifi.konpyutaika.com/v1
kind: NifiParameterContext
metadata:
  name: dataflow-parameters
spec:
  description: "It is a test"
  clusterRef:
    name: simplenifi
    namespace: nifi
  parameters:
    - name: test
      value: toto
      description: tutu
    - name: test2
      value: toto
      description: toto
```
### registry client
```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiRegistryClient
metadata:
  name: registryclient
spec:
  clusterRef:
    name: simplenifi
    namespace: nifi
  description: "cool demo"
  uri: "http://reg.local:18080/"
```
### flow
```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiDataflow
metadata:
  name: testing1234
spec:
#  parentProcessGroupID: "d55f90d4-018c-1000-0000-00004a2c0a5a"
  bucketId: "571b4f9e-7839-412e-be75-3b06aa55dc3e"
  flowId: "7880d07c-4991-4a53-ac44-95ffc9f28850"
  flowVersion: 2
  syncMode: once
  skipInvalidControllerService: true
  skipInvalidComponent: true
  clusterRef:
    name: simplenifi
    namespace: nifi
  registryClientRef:
    name: registryclient
    namespace: nifi
  flowPosition:
    posX: 12
    posY: 200
  parameterContextRef:
    name: dataflow-parameters
    namespace: nifi
  updateStrategy: drain

```

### What is the expected behavior?

one flow being deployed on the canvas

* this is the behavior in v.1.5.0 *

### What do you see instead?

two copies of the flow end up on the canvas

Only one seems to be the correct one:
* One takes the name of the resource (testing1234) the other takes the name of the flow in the registry
* One keps sync
* One enables/starts
* two events of Creating are generated in minikube dashboard, but one event of Created
* One object of type NifiDataflow is shown in the dashboard

nifikop log after deploy (not touching the canvas/ui):
```
{"level":"info","time":"2024-01-05T11:31:27.608Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to patch status for NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:27.608Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"ad3d2c79-c535-419f-9523-e58636d66ca5","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:27.704Z","logger":"controllers.NifiDataflow","caller":"controllers/nifidataflow_controller.go:412","msg":"Adding Finalizer for NifiDataflow testing1234"}
{"level":"info","time":"2024-01-05T11:31:27.713Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to update NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:27.713Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"ffa329e0-4b4d-4fc9-ba25-a5309dd327b3","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:27.742Z","logger":"controllers.NifiDataflow","caller":"controllers/nifidataflow_controller.go:412","msg":"Adding Finalizer for NifiDataflow testing1234"}
{"level":"info","time":"2024-01-05T11:31:27.831Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to patch status for NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:27.831Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"a6eee858-299f-45a8-8584-1c2b1c80e399","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:28.001Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to update NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:28.001Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"4ddf87ad-4a81-4442-8842-75bb532d8863","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:32.244Z","logger":"controllers.NifiCluster","caller":"controllers/nificluster_controller.go:135","msg":"NifiCluster starting reconciliation","clusterName":"simplenifi"}
{"level":"info","time":"2024-01-05T11:31:32.357Z","logger":"controllers.NifiCluster","caller":"nifi/nifi.go:284","msg":"Successfully reconciled cluster","component":"nifi","clusterName":"simplenifi","clusterNamespace":"nifi"}
{"level":"info","time":"2024-01-05T11:31:43.943Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to update status for NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:43.943Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"b0df95d6-6ba5-4319-b9cd-8b09f4b53292","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:44.200Z","logger":"controllers.NifiDataflow","caller":"controllers/controller_common.go:36","msg":"failed to update NifiDataflow testing1234"}
{"level":"error","time":"2024-01-05T11:31:44.200Z","caller":"controller/controller.go:329","msg":"Reconciler error","controller":"nifidataflow","controllerGroup":"nifi.konpyutaika.com","controllerKind":"NifiDataflow","nifiDataflow":{"name":"testing1234","namespace":"nifi"},"namespace":"nifi","name":"testing1234","reconcileID":"a4421d7f-2aab-49ee-bc37-783386964fdc","error":"Operation cannot be fulfilled on nifidataflows.nifi.konpyutaika.com \"testing1234\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"info","time":"2024-01-05T11:31:52.378Z","logger":"controllers.NifiCluster","caller":"controllers/nificluster_controller.go:135","msg":"NifiCluster starting reconciliation","clusterName":"simplenifi"}
{"level":"info","time":"2024-01-05T11:31:52.470Z","logger":"controllers.NifiCluster","caller":"nifi/nifi.go:284","msg":"Successfully reconciled cluster","component":"nifi","clusterName":"simplenifi","clusterNamespace":"nifi"}

```

### Possible solution

nifikop v1.5.0 works as expected already

even the same cluster and resources if `helm del' version 1.6.0 and install 1.5.0 next flow deployments work fine. The vice-versa is also true, removing 1.5.0 and installing 1.6.0 brings the duplicating behavior back

have tried deleting minikube profile and other restart/re-installs

### NiFiKop version

v1.6.0

### Golang version

not installed

### Kubernetes version

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

### NiFi version

1.23.2

### Additional context

Thanks a lot for the help
