### ISSUE TITLE
Refactor NifiCluster state management CRD Configuration

### ISSUE THREAD

**Issue by mh013370** [konpyutaika/nifikop#358]
### Is your feature request related to a problem?

No

### Describe the solution you'd like to see

With NiFi 2.0.0, the zookeeper configuration becomes optional with the addition of kubernetes-based cluster state management. Update the `NifiCluster` CRD to:

1. Make zookeeper configuration optional
2. Consolidate cluster state management configuration in the CRD

The following changes should be made to `v2alpha1/NifiCluster`:

```yaml
apiVersion: nifi.konpyutaika.com/v2alpha1
kind: NifiCluster
metadata:
  name: nifi-cluster
spec:
  stateManagement:
    kubernetes:
      identifier: my-cluster
    zookeeper:
      zkPath: /my-cluster
      zkAddress: zookeeper.zookeeper:2181
```

One of `kubernetes` or `zookeeper` should be configured and this should be enforced by the operator.

Update all documentation to reflect these changes.

### Additional context

This issue requires #359 to be completed first.

**Comment by juldrixx** [comment]
A field should exist to chose which one (zk or k8s) you want to use, no?

**Comment by mh013370** [comment]
I should give two examples. I believe it can be an either/or. So you'd configure either:

```yaml
apiVersion: nifi.konpyutaika.com/v2alpha1
kind: NifiCluster
metadata:
  name: nifi-cluster
spec:
  stateManagement:
    zookeeper:
      zkPath: /my-cluster
      zkAddress: zookeeper.zookeeper:2181
```

OR

```yaml
apiVersion: nifi.konpyutaika.com/v2alpha1
kind: NifiCluster
metadata:
  name: nifi-cluster
spec:
  stateManagement:
    zookeeper:
      zkPath: /my-cluster
      zkAddress: zookeeper.zookeeper:2181
```

And the existence of one or the other is how nifikop will know which to configure.
