### ISSUE TITLE
`nifi-cluster` helm chart template wraps two lines together

### ISSUE THREAD

**Issue by mikejoh** [konpyutaika/nifikop#399]
### What steps will reproduce the bug?

ArgoCD will constantly see a diff (Application will be Out Of Sync) between what the `nifi-cluster` helm chart renders and what's deployed in the cluster.

1. `git clone https://github.com/konpyutaika/nifikop.git`
2. `cd nifikop/helm/nifi-cluster`
3. `helm dependency build`
4. `helm template . -s templates/nifi-cluster.yaml`

### What is the expected behavior?

That the rendered manifest will look something like this instead:
```
spec:
  ...
  pod:
  singleUserConfiguration:
    secretRef:
      name: single-user-credentials
      namespace: nifi
    secretKeys:
      password: password
      username: username
  ...
```

### What do you see instead?

```
spec:
  ...
  pod:singleUserConfiguration:
    secretRef:
      name: single-user-credentials
      namespace: nifi
    secretKeys:
      password: password
      username: username
  ...
```
Notice that `singleUserConfiguration:` is inlined with `pod:`

### Possible solution

Not trimming trailing whitespace.

### NiFiKop version

v1.7.0-release

### Golang version

N/A

### Kubernetes version

N/A

### NiFi version

1.24.0
