### ISSUE TITLE
How to add groups only, to be used for openid?

### ISSUE THREAD

**Issue by AlexEndris** [konpyutaika/nifikop#460]
### Type of question

General Context

### Support question

Hi,
I'm trying to set up nifi using nifikop with keycloak. I've been able to login through keycloak but how do I set up the groups (and thus access) for those users, without having to add every single user as another k8s resource? All I need is a group mapping that, say, a user is part of the group "admin" he gets all rights, etc. No need to have user duplicates.

Can you maybe point me into the right direction?

### NiFi version

1.26.0

**Comment by mh013370** [comment]
This was only supported starting in Apache NiFi v1.23.0: https://issues.apache.org/jira/browse/NIFI-11492

As long as the group name in keycloak exactly matches the name of the group in NiFi, the user will be granted the group's authorizations.

**Comment by AlexEndris** [comment]
Thank you. That's good to know. Frankly, I'm really struggling running NiFi. I've so far only managed to get it running in Single User Mode (funnily enough authentication through OpenID works regardles). If I disable that (And disable the single user authorizer) I always get the error that the data/users.xml can't be found. This also doesn't change, if I actually add NifiUser (and NifiUsergroup) ressources to k8s.
Searches with google or here (or the old repo on github) didn't really help me, nor did the administrator's guide or samples.

**Comment by mh013370** [comment]
Have you seen this? https://github.com/konpyutaika/nifikop/tree/master/config/samples/keycloak-example

**Comment by AlexEndris** [comment]
Yes, I have. The issue, however, isn't the connection from Keycloak to Nifi, but having Nifi not terminate due to a file missing. Unless I've overlooked something within that sample.

**Comment by mh013370** [comment]
Yes, to have the operator create a group in NiFi for you, use the `NifiUserGroup` resource.

I've never deployed a NiFi with single user configuration and tried to migrate it to use a different authorizer. Perhaps @juldrixx knows whether this works?

You cannot use both the single user authorizer _and_ configure users and groups. It's one or the other.

**Comment by juldrixx** [comment]
I pretty sure it's not possible. When the single user authorizer is configured the user and group configuration aren't configurable in the NiFi UI so I'm guessing that it's not configurable.

**Comment by juldrixx** [comment]
> Yes, to have the operator create a group in NiFi for you, use the `NifiUserGroup` resource.
> 
> I've never deployed a NiFi with single user configuration and tried to migrate it to use the standard `managed-authorizer`. Perhaps @juldrixx knows whether this works?
> 
> You cannot use both the single user authorizer _and_ configure users and groups. It's one or the other.

I pretty sure it's not possible. When the single user authorizer is configured the user and group configuration aren't configurable in the NiFi UI so I'm guessing that it's not configurable.

**Comment by mh013370** [comment]
@AlexEndris My recommendation would be to deploy a fresh NiFi cluster and configure `NifiUser` and `NifiUserGroup` resources as needed. Just as in the keycloak example in the nifikop repo, you shouldn't need to configure anything related to single-user auth.

and like in NIFI-11492, as long as an authenticating user belongs to a group (coming from Keycloak) that exactly matches a group in NiFi, then that user will be authorized. See [this unit test](https://github.com/apache/nifi/blob/6e308f2cf1a93633b154b420bafa7a6819ca73fb/nifi-framework-bundle/nifi-framework/nifi-framework-authorization-providers/src/test/java/org/apache/nifi/authorization/StandardManagedAuthorizerTest.java#L370-L419) for how the logic works.

**Comment by AlexEndris** [comment]
@mh013370 As it's still in evaluation, I won't migrate anything and just create a new one. That's not a problem. I will have another look. Thank you very much for your help with this.
@juldrixx Last time I've tried not using the single user section (aka no configuration set so it should be 'false'), Nifi didn't start properly because it couldn't find the "../data/users.xml" file that's part of the file based authorizer which is used by the managed-authorizer. Even though I added a NifiUser and NifiUserGroup. Did I miss some configuration?

**Comment by juldrixx** [comment]
> @mh013370 As it's still in evaluation, I won't migrate anything and just create a new one. That's not a problem. I will have another look. Thank you very much for your help with this. @juldrixx Last time I've tried not using the single user section (aka no configuration set so it should be 'false'), Nifi didn't start properly because it couldn't find the "../data/users.xml" file that's part of the file based authorizer which is used by the managed-authorizer. Even though I added a NifiUser and NifiUserGroup. Did I miss some configuration?

Not sure why, but maybe you didn't configuration authentication method at all. At least one method must be configured between singleUser, OIDC, LDAP, SAML, etc.

**Comment by AlexEndris** [comment]
That might be it, although I could swear I had the OIDC with Keycloak configured. I'll have another stroll down the rabbit hole on Monday. Maybe it is as easy as that and I was just too deep to see it. Thank you!

**Comment by AlexEndris** [comment]
@juldrixx I've tried the following values for the nifi-cluster helm chart to instantiate the cluster. It keeps starting and terminating. 
```yaml
cluster:
  nodeUserIdentityTemplate: node-%d
  controllerUserIdentity: "nifi-controller"
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
      - type: "prometheus"
        name: "prometheus"
        containerPort: 9090
    sslSecrets: 
        tlsSecretName: "test"
        create: true
  externalServices:
    - name: "nifi-cluster-ip"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8443
            internalListenerName: "https"
  nifiProperties:
    webProxyHosts:
    - nifi.example.com
    overrideConfigs: |
      nifi.web.proxy.context.path=/
      nifi.sensitive.props.key=changemequickly
      nifi.security.user.oidc.discovery.url=https://keycloak.url.com
      nifi.security.user.oidc.client.id=nifi
      nifi.security.user.oidc.client.secret=myultrasecret
      nifi.security.user.oidc.additional.scopes=offline_access,email
      nifi.security.user.oidc.fallback.claims.identifying.user=preferred_username
zookeeper:
  enabled: true
```
the user and usergroup:
```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiUserGroup
metadata:
  name: test
  namespace: nifi-cluster
spec:
  clusterRef:
    name: nifi-cluster
    namespace: nifi-cluster
  usersRef:
    - name: test
  accessPolicies:
    # defines the kind of access policy, could be "global" or "component".
    - type: global
      # defines the kind of action that will be granted, could be "read" or "write"
      action: read
      # resource defines the kind of resource targeted by this access policies, please refer to the following page:
      #	https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#access-policies
      resource: /counters
---
apiVersion: nifi.konpyutaika.com/v1
kind: NifiUser
metadata:
  name: test
  namespace: nifi-cluster
spec:
  # identity field is use to define the user identity on NiFi cluster side,
  #	it use full when the user's name doesn't suite with Kubernetes resource name.
  identity: test@example.com
  # Contains the reference to the NifiCluster with the one the registry client is linked.
  clusterRef:
    name: nifi-cluster
    namespace: nifi-cluster
  # Whether or not the the operator also include a Java keystore format (JKS) with you secret
  includeJKS: false
  # Whether or not a certificate will be created for this user.
  createCert: true
```
This is what I get during start up in the logs:
```
ERROR [NiFi logging handler] org.apache.nifi.StdErr [java.io.FileNotFoundException: ../data/users.xml (No such file or directory)]
ERROR [NiFi logging handler] org.apache.nifi.StdErr  - with linked exception:
ERROR [NiFi logging handler] org.apache.nifi.StdErr Failed to start web server: Error creating bean with name 'niFiWebApiConfiguration': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.PrePostMethodSecurityConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.nifi.web.security.configuration.AuthenticationSecurityConfiguration': Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorizer': FactoryBean threw exception on object creation; nested exception is org.apache.nifi.authorization.exception.AuthorizerCreationException: javax.xml.bind.JAXBException
```

Am I missing something? According to what you said, this should suffice for it to run. I don't really know what I can do different here.
Logs from the operator itself just state, that it can't reach any node, which makes sense, if the node keeps throwing an exception during startup.

**Comment by jomach** [comment]
@AlexEndris  same error here

**Comment by Mx-Bx** [comment]
Hello @AlexEndris and @jomach,

I believe I’ve found a workaround for the issue. It appears that the users.xml file is not "available" despite being dynamically generated. By mounting a PVC to the location where the users.xml and other related files are generated automatically at runtime (e.g., the data directory), I was able to prevent the pod from terminating, and NiFi launched successfully.


Here is the configuration I used for reference:

```
---
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifi-cluster
  namespace: nifi
spec:
  service:
    headlessEnabled: true
  zkAddress: 'zookeeper.zookeeper.svc.cluster.local:2181'
  zkPath: '/simplenifi'
  clusterImage: 'apache/nifi:1.23.2'
  oneNifiNodePerNode: false
  managedAdminUsers:
    - identity: "admin@example.com"
      name: "admin"
  managedReaderUsers:
    - identity: "user@example.com"
      name: "user"
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: '/opt/nifi/nifi-current/logs'
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: 'longhorn'
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/data"
          name: data
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "longhorn"
            resources:
              requests:
                storage: 10Gi
      externalVolumeConfigs:
        - name: "keycloak-truststore-volume"
          mountPath: "/opt/nifi/nifi-current/conf/keycloak-truststore"
          secret:
            secretName: "keycloak-truststore"
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
    - id: 3
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
    sslSecrets:
      tlsSecretName: "nifi-tls"
      create: false
      clusterScoped: true
      issuerRef:
        kind: ClusterIssuer
        name: nifi-issuer
  externalServices:
    - name: "nifi-cluster"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8443
            internalListenerName: "https"
  readOnlyConfig:
    nifiProperties:
      webProxyHosts:
        - nifi.example.com:8443
      overrideConfigs: |
        nifi.security.user.oidc.additional.scopes=offline_access,email
        nifi.security.user.oidc.fallback.claims.identifying.user=preferred_username

        nifi.security.user.oidc.discovery.url=https://keycloak.example.com/realms/realm-name/.well-known/openid-configuration
        nifi.security.user.oidc.redirect.url=https://nifi.example.com/nifi-api/access/oidc/callback
        nifi.security.user.oidc.client.id=nifi
        nifi.security.user.oidc.client.secret=REDACTED_CLIENT_SECRET
        nifi.security.user.oidc.truststore.strategy=NIFI
        nifi.security.identity.mapping.pattern.dn=CN=([^,]*)(?:, (?:O|OU)=.*)?
        nifi.security.identity.mapping.value.dn=$1
        nifi.security.identity.mapping.transform.dn=NONE
        nifi.security.truststore=/opt/nifi/nifi-current/conf/keycloak-truststore/truststore.jks
        nifi.security.truststoreType=jks
        nifi.security.truststorePasswd=REDACTED_TRUSTSTORE_PASSWORD
        nifi.sensitive.props.key=REDACTED_SENSITIVE_KEY
    bootstrapProperties:
      nifiJvmMemory: "512m"
      overrideConfigs: |
        java.arg.15=-Djavax.net.ssl.trustStore=/opt/nifi/nifi-current/conf/keycloak-truststore/truststore.jks
        java.arg.16=-Djavax.net.ssl.trustStorePassword=REDACTED_TRUSTSTORE_PASSWORD

```

I hope this helps! Let me know if further clarification is needed.
