### ISSUE TITLE
[helm chart] "nifikop-" prefix causes certificate names to be too long

### ISSUE THREAD

**Issue by Nickmman** [konpyutaika/nifikop#461]
### What steps will reproduce the bug?

- Deploy via helm with the following values:
```
cluster:
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
    sslSecrets:
      tlsSecretName: "nifi-ssl-certs"
      create: true
  nameOverride: "nifi-cluster"
  pod:
    readinessProbe:
      tcpSocket:
        port: 6007
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 6007
      initialDelaySeconds: 15
      periodSeconds: 10
  zkAddress: zookeeper:2181
```
- Watch as `nameOverride` is ignored and certificates want to be created with the `nikifop-` prefix anyway:
```
{
  "level": "error",
  "time": "2024-09-09T22:16:05.286Z",
  "caller": "controller/controller.go:329",
  "msg": "Reconciler error",
  "controller": "nifiuser",
  "controllerGroup": "nifi.konpyutaika.com",
  "controllerKind": "NifiUser",
  "nifiUser": {
    "name": "nifikop-nifi-cluster-1-node.nifikop-nifi-cluster-headless.nifi.svc.cluster.local",
    "namespace": "nifi"
  },
  "namespace": "nifi",
  "name": "nifikop-nifi-cluster-1-node.nifikop-nifi-cluster-headless.nifi.svc.cluster.local",
  "reconcileID": "437f94fb-863c-46c3-a508-2ba28d2dfbbf",
  "error": "could not create user certificate: admission webhook \"webhook.cert-manager.io\" denied the request: spec.commonName: Toolong: must have at most 64 bytes",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"
}
```

### What is the expected behavior?

The `nifikop-` prefix is dropped from the naming scheme.

### What do you see instead?

Watch as `nameOverride` is ignored and certificates want to be created with the `nikifop-` prefix anyway:
```
{
  "level": "error",
  "time": "2024-09-09T22:16:05.286Z",
  "caller": "controller/controller.go:329",
  "msg": "Reconciler error",
  "controller": "nifiuser",
  "controllerGroup": "nifi.konpyutaika.com",
  "controllerKind": "NifiUser",
  "nifiUser": {
    "name": "nifikop-nifi-cluster-1-node.nifikop-nifi-cluster-headless.nifi.svc.cluster.local",
    "namespace": "nifi"
  },
  "namespace": "nifi",
  "name": "nifikop-nifi-cluster-1-node.nifikop-nifi-cluster-headless.nifi.svc.cluster.local",
  "reconcileID": "437f94fb-863c-46c3-a508-2ba28d2dfbbf",
  "error": "could not create user certificate: admission webhook \"webhook.cert-manager.io\" denied the request: spec.commonName: Toolong: must have at most 64 bytes",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"
}
```

### NiFiKop version

v1.10.0

### Golang version

Whatever is bundled with the container image

### Kubernetes version

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7-gke.1104000

### Additional context

The docs say:

> When using [cert-manager Issuer](https://cert-manager.io/docs/concepts/issuer/), please make sure that the hostname (default clusterName-id-node.namespace.svc.cluster.local) for the nodes in cluster is 64 bytes or less, otherwise the webhook of cert-manager will fail. You can try to use shorter name for NiFiCluster or modify nodeUserIdentityTemplate to keep the name length under 64 bytes.

When setting `cluster.nodeUserIdentityTemplate` to the suggested value of `"node-%d-"`, the creation of the certificates/secrets fail because it cannot end in `-`. When removing the trailing `-`, the certificate gets created but the pod names are missing the last `-` between the name of the pod and the unique identifier.
