### ISSUE TITLE
Allow NifiCluster Pod to be suspended when process crashes, to allow for debugging

### ISSUE THREAD

**Issue by ChrisSamo632** [konpyutaika/nifikop#492]
### Is your feature request related to a problem?

Configuration problems during NiFi startup can result in the NiFi process crashing, for example if no `nifi.sensitive.props.key` is defined for Cluster nodes.

The Pod is immediately terminated and replaced with a new Pod by NiFiKop, which will quickly fail again. It is very difficult to retrieve the logs/any information as to why the Pod keep crashing.

### Describe the solution you'd like to see

A way to suspend the Pod for a set period before it is deleted by NiFiKop, e.g. a setting in the operator that waits for a set time before deleting and re-creating the Pod, to allow for log retrieval

**Comment by juldrixx** [comment]
Hi @ChrisSamo632, you can use sidecars to use to tails the logs with a shared volume with the nifi container. So if NiFi crashes, you still have access to the logs. And you can add as much sidecar as you want with each one of the tailing a specific log file.  Personnaly, that's what we do.

**Comment by juldrixx** [comment]
Something like:

```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifikop
spec:
  ...
  nodeConfigGroups:
    default_group:
      ...
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: ssd-wait
  sidecarConfigs:
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      image: busybox:1.36
      name: app-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
```
