### ISSUE TITLE
Mounting existing PVC in ReadOnlyMany mode to all nodes

### ISSUE THREAD

**Issue by lookIce** [konpyutaika/nifikop#540]
### Type of question

Implementation Assistance

### Support question

Is it possible to include in configuration parameter to mount some precreated PVC which will be used in ReadOnlyMany mode by all cluster nodes. Currently as per documentation it is possible to create PVC using storageConfiguration or mount some volumes using ExternalVolumeConfig, but here I could manage only ConfigMaps, Secrets, EmtiDir, but could not find way to use existing PVC.

### NiFiKop version

v1.12.0

### NiFi version

1.28.0

**Comment by juldrixx** [comment]
Hi, you are right there shoud not be any way to do it currently (or I missed something). But yes, it could great to add the possibility to do it.

If you can, feel free to make a PR for it.
Or if I get some time, I may look into it in the future.

**Comment by juldrixx** [comment]
Sorry, I get to back, I misspoke. In fact, you can use `externalVolumeConfigs` to do what you want.
You just do something like:

```yaml
      externalVolumeConfigs:
        - name: my-pvc
          persistentVolumeClaim:
            claimName: my-pvc
          mountPath: /my-pvc
```
