### ISSUE TITLE
Nifi 2 out of box

### ISSUE THREAD

**Issue by fliot** [konpyutaika/nifikop#547]
### Type of question

Best Practices

### Support question

Hi, I'm trying to use Nifikop to deploy a Nifi 2.x cluster.

The documentation assumes this should work,
https://konpyutaika.github.io/nifikop/docs/4_compatibility_versions

But all examples in documentation are targeting Nifi 1.x (with Zookeeper), but never Nifi 2.x (with or without optional Zookeeper).

Is there anything similar to simplenificluster sample with overrideConfigs somewhere ?

Thanks in advance.

**Comment by juldrixx** [comment]
To make it works in NiFi 2, you will need to remove the prometheus port (9092) to prevent the operator to create a reporting task that doesn't exist anymore.

And if you don't want to use Zookeeper, you must set the property `clusterManager` to `kubernetes`: https://konpyutaika.github.io/nifikop/docs/5_references/1_nifi_cluster/#clustermanagertype

**Comment by juldrixx** [comment]
Here is a configuration of cluster to work in local kubernetes like one with colima:

```yaml
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifikop
  namespace: nifikop
spec:
  clusterImage: apache/nifi:2.3.0
  nodeUserIdentityTemplate: node-%d-nifikop
  externalServices:
    - name: nifikop
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
          - internalListenerName: s2s
            port: 10000
        type: LoadBalancer
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        name: http
        type: http
      - containerPort: 6007
        name: cluster
        type: cluster
      - containerPort: 10000
        name: s2s
        type: s2s
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  managedAdminUsers:
    - identity: julien.guitton@nifikop.com
      name: jguitton
  nodeConfigGroups:
    default_group:
      fsGroup: 1337
      isNode: true
      resourcesRequirements:
        limits:
          cpu: "4"
          memory: 3Gi
        requests:
          cpu: "4"
          memory: 2Gi
      serviceAccountName: nifikop-cluster
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/content_repository
          name: content-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/extensions
          name: extensions-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  nodes:
    - id: 0
      labels:
        nifi_cr: nifikop
        nifi_node_group: default_group
      nodeConfigGroup: default_group
  propagateLabels: false
  readOnlyConfig:
    bootstrapProperties:
      nifiJvmMemory: 3g
      overrideConfigs: |
        # Java 8 Tuning see https://community.hortonworks.com/articles/7882/hdfnifi-best-practices-for-setting-up-a-high-perfo.html for references
        java.arg.7=-XX:ReservedCodeCacheSize=256m
        java.arg.8=-XX:+UseCodeCacheFlushing
    maximumTimerDrivenThreadCount: 40
    nifiProperties:
      overrideConfigs: |
        nifi.nar.library.autoload.directory=../extensions
        nifi.sensitive.props.key=nifikopnifikopnifikop
      webProxyHosts:
        - nifikop.127.0.0.1.nip.io:8080
        - nifikop.127.0.0.1.nip.io
  service:
    headlessEnabled: true
  sidecarConfigs:
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      image: busybox:1.36
      name: app-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-bootstrap.log
      image: busybox:1.36
      name: bootstrap-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-user.log
      image: busybox:1.36
      name: user-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
  clusterManager: kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifikop
  namespace: nifikop
  annotations:
    nginx.org/ssl-services: nifikop
    nginx.org/lb-method: ip_hash
spec:
  rules:
    - host: nifikop.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: nifikop
                port:
                  number: 8080
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifikop-cluster
  namespace: nifikop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifikop
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifikop
subjects:
  - kind: ServiceAccount
    name: nifikop-cluster
    namespace: nifikop
roleRef:
  kind: Role
  name: nifikop-cluster
  apiGroup: rbac.authorization.k8s.io
```
