### ISSUE TITLE
Unable to open Nifi Web Ui after getting it running

### ISSUE THREAD

**Issue by K7-N** [konpyutaika/nifikop#578]
### Type of question

Implementation Assistance

### Support question

I am trying to run Nifi on my 16GB 1TB Windows Laptop on Minikube in Docker Desktop
the issue i am facing is that after setting up and getting the pod running when i tunnel it with minikube i simply get site cant be reached for the link received 

I got nifi running once before but i am unable to recreate that now.

i have attached Logs of my Nifi instance as well 

These are the step in order i preformed to get the Nifi running

```
 minikube start --memory=6500 --cpus=6 --kubernetes-version=v1.33.1 

kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.2/cert-manager.yaml

kubectl create namespace nifi

helm install nifikop oci://ghcr.io/konpyutaika/helm-charts/nifikop --namespace nifi --version 1.14.0 --set image.tag=v1.14.0-release --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set "namespaces={nifi}"

helm install zookeeper oci://registry-1.docker.io/bitnamicharts/zookeeper --namespace=zookeeper --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set global.storageClass=standard --set networkPolicy.enabled=true --set replicaCount=3 --create-namespace

kubectl apply -f NifiCluster3.yaml -n nifi
```

My Nifi Cluster Configuration is

```
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifikop
  namespace: nifi
spec:
  clusterImage: apache/nifi:2.3.0
  nodeUserIdentityTemplate: node-%d-nifikop
  externalServices:
    - name: nifikop
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
          - internalListenerName: s2s
            port: 10000
        type: NodePort
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        name: http
        type: http
      - containerPort: 6007
        name: cluster
        type: cluster
      - containerPort: 10000
        name: s2s
        type: s2s
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  nodeConfigGroups:
    default_group:
      fsGroup: 1337
      isNode: true
      resourcesRequirements:
        limits:
          cpu: "3"
          memory: 2.5Gi
        requests:
          cpu: "3"
          memory: 2Gi
      serviceAccountName: nifikop-cluster
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/content_repository
          name: content-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/extensions
          name: extensions-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  nodes:
    - id: 0
      labels:
        nifi_cr: nifikop
        nifi_node_group: default_group
      nodeConfigGroup: default_group
  propagateLabels: false
  readOnlyConfig:
    bootstrapProperties:
      nifiJvmMemory: 3g
      overrideConfigs: |
        # Java 8 Tuning see https://community.hortonworks.com/articles/7882/hdfnifi-best-practices-for-setting-up-a-high-perfo.html for references
        java.arg.7=-XX:ReservedCodeCacheSize=256m
        java.arg.8=-XX:+UseCodeCacheFlushing
    maximumTimerDrivenThreadCount: 40
    nifiProperties:
      overrideConfigs: |
        nifi.nar.library.autoload.directory=../extensions
        nifi.sensitive.props.key=nifikopnifikopnifikop
      webProxyHosts:
        - nifikop.127.0.0.1.nip.io:8080
        - nifikop.127.0.0.1.nip.io
  service:
    headlessEnabled: true
  sidecarConfigs:
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      image: busybox:1.36
      name: app-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-bootstrap.log
      image: busybox:1.36
      name: bootstrap-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-user.log
      image: busybox:1.36
      name: user-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
  clusterManager: kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifikop
  namespace: nifi
  annotations:
    nginx.org/ssl-services: nifikop
    nginx.org/lb-method: ip_hash
spec:
  rules:
    - host: nifikop.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: nifikop
                port:
                  number: 8080
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifikop-cluster
  namespace: nifi
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifi
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifi
subjects:
  - kind: ServiceAccount
    name: nifikop-cluster
    namespace: nifi
roleRef:
  kind: Role
  name: nifikop-cluster
  apiGroup: rbac.authorization.k8s.io

```

[NifiLogs.txt](https://github.com/user-attachments/files/20493509/NifiLogs.txt)

### NiFiKop version

v1.14.0-release

### Golang version

not using Golang

### Kubernetes version

Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1

### NiFi version

2.3.0
