### ISSUE TITLE
New PVCs created when NifiCluster is deleted, even though the reclaimPolicy is set to "Retain"

### ISSUE THREAD

**Issue by munira-jo** [konpyutaika/nifikop#589]
### What steps will reproduce the bug?

1. Environment:

We have Nifikop deployed on EKS via ArgoCD. 

2. This the NifiCluster:

```
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifi
  namespace: {{ .Release.Namespace }}
spec:
  service:
    headlessEnabled: true
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
      traefik.ingress.kubernetes.io/service.sticky.cookie: 'true'
      traefik.ingress.kubernetes.io/service.sticky.cookie.secure: 'true'
    labels:
      cluster-name: nifi
  clusterManager: kubernetes
  externalServices:
    - metadata:
        labels:
          cluster-name: nifi
      name: de-nifi-new-svc
      spec:
        portConfigs:
          - internalListenerName: https
            port: 8443
        type: ClusterIP
        internalTrafficPolicy: Cluster
  clusterImage: "apache/nifi:2.4.0"
  initContainerImage: "bash:5.2.2"
  oneNifiNodePerNode: true
  singleUserConfiguration:
    enabled: true
    authorizerEnabled: false
  readOnlyConfig:
    authorizerConfig:
      replaceTemplateConfigMap:
        data: authorizers.xml
        namespace: {{ .Release.Namespace }}
        name: raw
    logbackConfig:
      replaceConfigMap:
        data: logback.xml
        namespace: {{ .Release.Namespace }}
        name: raw
    nifiProperties:
      webProxyHosts: 
      - my-url
      overrideConfigMap:
        data: nifi.properties
        namespace: {{ .Release.Namespace }}
        name: raw
      overrideSecretConfig:
        data: nifi.properties
        name: my-secret-name
        namespace: {{ .Release.Namespace }}
  pod:
    labels:
      cluster-name: nifi
  nodeConfigGroups:
    group1:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: nifisa
      resourcesRequirements:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 3Gi
      storageConfigs:
        - mountPath: /opt/nifi/data
          name: data
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 0.5Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/extensions
          name: extensions-repository
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 0.5Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 3Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 0.5Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/content_repository
          name: content-repository
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 3Gi
            storageClassName: general-purpose
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository
          reclaimPolicy: Retain
          pvcSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 3Gi
            storageClassName: general-purpose
  nodes:
    - id: 0
      nodeConfigGroup: "group1"
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 0
    - id: 1
      nodeConfigGroup: "group1"
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 1
    - id: 2
      nodeConfigGroup: "group1"
      readOnlyConfig:
        nifiProperties:
          overrideConfigs: |
            nifi.ui.banner.text=NiFiKop - Node 2
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - containerPort: 8443
        type: https
        name: https
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 6342
        type: load-balance
        name: load-balance
    sslSecrets:
      create: true
      issuerRef:
        name: awspca
        kind: AWSPCAClusterIssuer
        group: awspca.cert-manager.io

```

### What is the expected behavior?

The expected behaviour is for the same PVCs to be re-used when the NifiCluster is deleted since the `reclaimPolicy` is set to `Retain`. 

### What do you see instead?

When the NifiCluster is deleted, new PVCs seem to be created.

### NiFiKop version

v1.13.0-release

### Golang version

go version go1.24.1 darwin/arm64

### Kubernetes version

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.13-eks-5d4a308

### NiFi version

2.4.0
