### ISSUE TITLE
Cannot deploy demo with GKE 

### ISSUE THREAD

**Issue by zepouet** [konpyutaika/nifikop#94]
## Bug Report

**What did you do?**

````
kubectl create clusterrolebinding cluster-admin-binding  \
--clusterrole=cluster-admin  \
--user=$(gcloud config get-value core/account)


helm install -n zookeeper zookeeper bitnami/zookeeper \
    --set resources.requests.memory=256Mi \
    --set resources.requests.cpu=250m \
    --set resources.limits.memory=256Mi \
    --set resources.limits.cpu=250m \
    --set global.storageClass=standard \
    --set networkPolicy.enabled=true \
    --set replicaCount=3

kubectl apply -f \
    https://github.com/jetstack/cert-manager/releases/download/v1.7.2/cert-manager.yaml

kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nificlusters.yaml
kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nifiusers.yaml
kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nifiusergroups.yaml
kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nifidataflows.yaml
kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nifiparametercontexts.yaml
kubectl apply -f https://raw.githubusercontent.com/konpyutaika/nifikop/master/config/crd/bases/nifi.konpyutaika.com_nifiregistryclients.yaml

helm install nifikop \
    oci://ghcr.io/konpyutaika/helm-charts/nifikop \
    --namespace=nifi \
    --version 0.10.0 \
    --set image.tag=v0.10.0-release \
    --set resources.requests.memory=256Mi \
    --set resources.requests.cpu=250m \
    --set resources.limits.memory=256Mi \
    --set resources.limits.cpu=250m \
    --set namespaces={"nifi"}
````

Then `kubectl apply -f mystorageclass.yaml`

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mystorageclass
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

then

````
apiVersion: nifi.konpyutaika.com/v1alpha1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  service:
    headlessEnabled: true
  zkAddress: "zookeeper.zookeeeper:2181"
  zkPath: "/simplenifi"
  clusterImage: "apache/nifi:1.15.3"
  oneNifiNodePerNode: false
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "mystorageclass"
            resources:
              requests:
                storage: 10Gi
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - type: "http"
        name: "http"
        containerPort: 8080
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
      - type: "prometheus"
        name: "prometheus"
        containerPort: 9090
  externalServices:
    - name: "clusterip"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8080
            internalListenerName: "http"
      metadata:
        annotations:
          toto: tata
    - name: "loadbalancer"
      spec:
        type: LoadBalancer
        portConfigs:
          - port: 8080
            internalListenerName: "http"
      metadata:
        annotations:
          toto: tata
        labels:
          titi: tutu
    - name: "nodepart"
      spec:
        type: NodePort
        portConfigs:
          - port: 8080
            internalListenerName: "http"
      metadata:
        annotations:
          toto: tata
        labels:
          titi: tutu

````

To finish 

```
kubectl create -f config/samples/simplenificluster.yaml -n nifi
```

**What did you expect to see?**

Pod initializing and Load Balancer up and ready.

**What did you see instead? Under which circumstances?**

Always loop about pods not initialized.

````
NAME                       READY   STATUS     RESTARTS   AGE
nifikop-5d656f8798-7llpr   1/1     Running    0          9m3s
simplenifi-1-nodepph8n     0/1     Init:0/1   0          3m19s
simplenifi-2-node5b5d2     0/1     Init:0/1   0          3m19s
````

```
Events:
  Type    Reason                  Age   From                     Message
  ----    ------                  ----  ----                     -------
  Normal  Scheduled               2m6s  default-scheduler        Successfully assigned nifi/simplenifi-1-nodepph8n to gke-nifikop-default-pool-66ad738b-hpvq
  Normal  SuccessfulAttachVolume  2m1s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-fa4cad3e-c8bd-4ecf-ae2d-7923fa35ea4c"
  Normal  Pulling                 117s  kubelet                  Pulling image "busybox"
  Normal  Pulled                  116s  kubelet                  Successfully pulled image "busybox" in 914.077964ms
  Normal  Created                 116s  kubelet                  Created container zookeeper
  Normal  Started                 116s  kubelet                  Started container zookeeper
```

Last events with `kubectl get events -n nifi`

````
4m41s       Normal   ProvisioningSucceeded    persistentvolumeclaim/simplenifi-1-storage62hzz   Successfully provisioned volume pvc-fa4cad3e-c8bd-4ecf-ae2d-7923fa35ea4c using kubernetes.io/gce-pd
4m40s       Normal   Scheduled                pod/simplenifi-2-node5b5d2                        Successfully assigned nifi/simplenifi-2-node5b5d2 to gke-nifikop-default-pool-66ad738b-bv1b
4m35s       Normal   SuccessfulAttachVolume   pod/simplenifi-2-node5b5d2                        AttachVolume.Attach succeeded for volume "pvc-aa9279fe-7479-4124-bf01-041c39da0968"
4m31s       Normal   Pulling                  pod/simplenifi-2-node5b5d2                        Pulling image "busybox"
4m30s       Normal   Pulled                   pod/simplenifi-2-node5b5d2                        Successfully pulled image "busybox" in 901.229379ms
4m30s       Normal   Created                  pod/simplenifi-2-node5b5d2                        Created container zookeeper
4m30s       Normal   Started                  pod/simplenifi-2-node5b5d2                        Started container zookeeper
4m44s       Normal   WaitForFirstConsumer     persistentvolumeclaim/simplenifi-2-storage8864m   waiting for first consumer to be created before binding
4m41s       Normal   ProvisioningSucceeded    persistentvolumeclaim/simplenifi-2-storage8864m   Successfully provisioned volume pvc-aa9279fe-7479-4124-bf01-041c39da0968 using kubernetes.io/gce-pd
````

**Environment**

* nifikop version:

1.15.3

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:50:27Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE classic with 3 N2 2vcpu and 8 Go each one

```
gke-nifikop-default-pool-66ad738b-bv1b   Ready    <none>   90m   v1.21.10-gke.2000   10.164.0.2    34.147.107.222   Container-Optimized OS from Google   5.4.170+         containerd://1.4.8
gke-nifikop-default-pool-66ad738b-hllx   Ready    <none>   90m   v1.21.10-gke.2000   10.164.0.4    34.91.50.57      Container-Optimized OS from Google   5.4.170+         containerd://1.4.8
gke-nifikop-default-pool-66ad738b-hpvq   Ready    <none>   90m   v1.21.10-gke.2000   10.164.0.3    34.90.187.93     Container-Optimized OS from Google   5.4.170+         containerd://1.4.8
````

* NiFi version:

1.15.3

**Additional context**

I don't understand if the problems occurs with Zookeeper installation or configuration.
It seems to try to create and start zookeeper.

**Comment by zepouet** [comment]
It seems that there is an error about `zkAddress: "zookeeper.zookeeeper:2181"`
Three 3 are written into **zookeeeper**

It correct it and after the pod tries to start

````
➜  nifikop git:(master) ✗ kubectl -n nifi logs simplenifi-1-nodeprw5q nifi
I0509 22:07:02.332184    7303 versioner.go:58] no Auth Provider found for name "gcp"
Waiting for host to be reachable
failed to reach simplenifi-1-node.simplenifi-headless.nifi.svc.cluster.local:8080
Found: , expecting: 10.36.1.28
Found : 10.36.1.28
Ip match for 10.36.1.28
Hostname is successfully binded withy IP adress
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: simplenifi-headless.nifi.svc.cluster.local
* Closing connection 0
curl: (6) Could not resolve host: simplenifi-headless.nifi.svc.cluster.local

Java home: /usr/local/openjdk-8
NiFi home: /opt/nifi/nifi-current

Bootstrap Config File: /opt/nifi/nifi-current/conf/bootstrap.conf
```

**Comment by michael81877** [comment]
So did correcting the zookeeper path resolve your issue? Or are you still experiencing problems?

**Comment by zepouet** [comment]
> So did correcting the zookeeper path resolve your issue? Or are you still experiencing problems?
> 
> The **zookeeeper** typo in the `simplenificluster` should be addressed regardless: https://github.com/konpyutaika/nifikop/blob/master/config/samples/simplenificluster.yaml#L8

Thanks Michael, I correct my previous comment to be clear. The pod has a problem after about the host resolution simplenifi-headless.nifi.svc.cluster.local

Nicolas

**Comment by PDEUXA** [comment]
I tried to push the following config file (which is working for me , whereas the one on master branch is not); thus if you could do a PR and review it (I do not have rights on the repo)

```yaml
apiVersion: nifi.konpyutaika.com/v1alpha1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: simplenifi
  zkAddress: "zookeeper.zookeeper:2181"
  zkPath: /simplenifi
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-simplenifi
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
        type: LoadBalancer
  clusterImage: 'apache/nifi:1.12.1'
  initContainerImage: 'busybox:1.34.0'
  oneNifiNodePerNode: true
  pod:
    labels:
      cluster-name: simplenifi
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: default
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/nifi-current/extensions
          name: extensions
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Mi
            storageClassName: "standard"
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Mi
            storageClassName: "standard"
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Mi
            storageClassName: "standard"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodeUserIdentityTemplate: n-%d
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  readOnlyConfig:
    zookeeperProperties:
      overrideSecretConfig:
        data: zookeeper.properties
        name: simplenifi
        namespace: nifi
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        type: http
        name: http
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 9090
        type: prometheus
        name: prometheus
```
